trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- script: ls -l $(Build.Repository.LocalPath)/hello_world

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
          echo "Downloading deps and creating zip file"
          pip install -r hello_world/requirements.txt --target ./package pyyaml
          echo "Checking package folder"
          cd package
          ls -l
          echo "Adding deps to zip"
          zip -r9 ../lambda_function.zip .
          cd ..
          echo "Adding function to zip"
          cd hello_world
          chmod 755 lambda_function.py
          zip -g ../lambda_function.zip lambda_function.py
          zip -g ../lambda_function.zip sqldatabase.yml
          pwd
          ls -l

- task: LambdaDeployFunction@1
  displayName: 'Deploying to AWS Lambda'
  #condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    awsCredentials: 'AWS (Hack4SSB)'
    regionName: 'eu-central-1'
    deploymentMode: 'codeonly'
    functionName: 'arn:aws:lambda:eu-central-1:205984356518:function:helloWorld'
    codeLocation: 'localfile'
    localZipFile: 'lambda_function.zip'
    
