# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'AWS (Hack4SSB)'
    regionName: 'eu-central-1'
    deploymentMode: 'codeonly'
    functionName: 'arn:aws:lambda:eu-central-1:205984356518:function:helloWorld'
    codeLocation: 'localfile'
    localZipFile: '.'