trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

steps:
- script: ls -l $(Build.Repository.LocalPath)/hello_world

- task: LambdaNETCoreDeploy@1
  inputs:
    awsCredentials: 'AWS (Hack4SSB)'
    regionName: 'eu-central-1'
    command: 'deployFunction'
    packageOnly: true
    packageOutputFile: '$(Pipeline.Workspace)/lambda_function.zip'
    lambdaProjectPath: '$(Build.Repository.LocalPath)/lambda_function.py'

#- task: ArchiveFiles@2
#  displayName: 'Creating zip file'
#  inputs:
#    rootFolderOrFile: $(Build.Repository.LocalPath)/hello_world
#    includeRootFolder: false
#    archiveType: 'zip'
#    archiveFile: '$(Pipeline.Workspace)/lambda_function.zip'
#    replaceExistingArchive: true

- task: LambdaDeployFunction@1
  displayName: 'Deploying to AWS Lambda'
  #condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    awsCredentials: 'AWS (Hack4SSB)'
    regionName: 'eu-central-1'
    deploymentMode: 'codeonly'
    functionName: 'arn:aws:lambda:eu-central-1:205984356518:function:helloWorld'
    codeLocation: 'localfile'
    localZipFile: '$(Pipeline.Workspace)/lambda_function.zip'
    
